// supervisedBy: array of internal person ids (co-supervision supported), or null.
// externalSupervisors (optional): [{ name, title, url }] for supervisors/co-supervisors
// outside the lab who don't have their own profile card — url is optional.
// incoming (optional): true for a person who hasn't arrived yet — shows under their
// supervisor's "Incoming Members" profile section instead of "Current Students".
window.PEOPLE_DATA = {
  people: [
    {
      id: "gilles-brassard",
      photo: "gilles.jpg",
      profilePhotoFit: "contain",
      supervisedBy: null,
      supervises: ["samuel-ducharme", "remi-ligez", "muxue-guo"],
      formerStudents: [
        { name: "Claude Crépeau", role: "master's 1997" },
        { name: "Anne Broadbent", role: "PhD 2004" },
        { name: "Pierre Marcoux", role: "PhD 1991 · Complexity Theory, Computability", url: "https://marcoux.ebsi.umontreal.ca/" },
      ],
      teaching: [
        {
          code: "IFT 3155/IFT 6155",
          en: {
            name: "Informatique quantique",
            detail: "Undergraduate / Graduate · DIRO · Fall 2025/Fall 2026",
          },
          fr: {
            name: "Informatique quantique",
            detail:
              "Premier cycle / Cycles supérieurs · DIRO · Automne 2025/Automne 2026",
          },
        },
      ],
      en: {
        eyebrow: "Faculty",
        nameFirst: "Gilles",
        nameLast: "Brassard",
        rank: "Full Professor · DIRO, Université de Montréal",
        researchAreaTags: ["Quantum Cryptography", "Quantum Foundations"],
        email: "brassard@iro.umontreal.ca",
        links: [
          {
            label: "Personal Website",
            url: "https://www.iro.umontreal.ca/~brassard/CV/",
          },
        ],
        bio: [
          "Gilles Brassard is a Full Professor at the Université de Montréal, where he has been a faculty member since 1979, and is the recepient of the 2025 Turing Award (the computer science equivalent of the Nobel Prize). Together with Charles H. Bennett, he co-invented quantum cryptography with the BB84 quantum key establishment protocol.",
          "Brassard has made groundbreaking contributions to quantum information and computation, including the discovery of quantum teleportation, entanglement distillation, amplitude amplification and quantum pseudo-telepathy, shaping the mathematical foundations of the field.",
        ],
        researchInterests: [
          "Quantum cryptography and quantum key establishment",
          "Quantum algorithms",
          "Quantum information",
          "Foundations of quantum theory",
        ],
      },
      fr: {
        eyebrow: "Corps professoral",
        nameFirst: "Gilles",
        nameLast: "Brassard",
        rank: "Professeur titulaire · DIRO, Université de Montréal",
        researchAreaTags: ["Cryptographie quantique", "Fondements quantiques"],
        email: "brassard@iro.umontreal.ca",
        links: [
          {
            label: "Site web personnel",
            url: "https://www.iro.umontreal.ca/~brassard/CV/",
          },
        ],
        bio: [
          "Gilles Brassard est Professeur titulaire à l'Université de Montréal, où il est membre du corps professoral depuis 1979, et titulaire de la Chaire de recherche du Canada en science de l'information quantique. Avec Charles H. Bennett, il a co-inventé la cryptographie quantique avec le protocole d'établissement de clés quantiques BB84.",
          "Brassard a apporté des contributions majeures à l'information et au calcul quantiques, notamment la découverte de la téléportation quantique, la distillation d'intrication, l'amplification d'amplitude et la pseudo-télépathie quantique, façonnant ainsi les fondements mathématiques du domaine.",
        ],
        researchInterests: [
          "Cryptographie quantique et établissement de clés quantiques",
          "Algorithmes quantiques",
          "Information quantique",
          "Fondements de la théorie quantique",
        ],
      },
    },
    {
      id: "louis-salvail",
      photo: "louis_salvail.jpeg",
      supervisedBy: null,
      supervises: [
        "charlie-pilon-senterre",
        "mohammed-barhoush",
        "louis-charles-thibodeau",
        "florian-le-mouel",
        "khaireddine-medhioub",
      ],
      formerStudents: [],
      teaching: [
        {
          code: "IFT 6180",
          en: {
            name: "Cryptologie : théorie et applications",
            detail: "Graduate · DIRO · Winter 2026/Winter 2027",
          },
          fr: {
            name: "Cryptologie : théorie et applications",
            detail: "Cycles supérieurs · DIRO · Hiver 2026/Hiver 2027",
          },
        },
        {
          code: "IFT 2105",
          en: {
            name: "Introduction à l'informatique théorique",
            detail: "Undergraduate · DIRO . Fall 2025/Fall 2026",
          },
          fr: {
            name: "Introduction à l'informatique théorique",
            detail: "Premier cycle · DIRO . Automne 2025/Automne 2026",
          },
        },
        {
          code: "IFT 1065",
          en: {
            name: "Structures discrètes en informatique",
            detail: "Undergraduate · DIRO . Winter 2027",
          },
          fr: {
            name: "Structures discrètes en informatique",
            detail: "Premier cycle · DIRO . Hiver 2027",
          },
        },
      ],
      en: {
        eyebrow: "Faculty",
        nameFirst: "Louis",
        nameLast: "Salvail",
        rank: "Full Professor · DIRO, Université de Montréal",
        researchAreaTags: ["Quantum Cryptography"],
        email: "salvail@iro.umontreal.ca",
        links: [
          {
            label: "Personal Website",
            url: "https://www.iro.umontreal.ca/~salvail/Fiche%20personnelle.html",
          },
        ],
        bio: [
          "I obtained my PhD from the Université de Montréal in 1998. In the language of scientific lineages, my fathers are Gilles Brassard and Claude Crépeau. Strangely, Gilles is also my grandfather since Claude is my brother. In academia, these affiliations are entirely natural.",
          "I began my university career at Aarhus University in Denmark from 1998 to 2008. I had the incredible fortune of working with Ivan Damgaard, to whom I owe a great deal. It was at Aarhus University that I learned the fundamentals of classical cryptography that are so useful to me today.",
          "I joined the Department of Computer Science at the Université de Montréal in June 2008.",
        ],
        researchInterests: [
        "Quantum cryptography",
        "Classical cryptography",
        "Quantum information theory",
        ],
      },
      fr: {
        eyebrow: "Corps professoral",
        nameFirst: "Louis",
        nameLast: "Salvail",
        rank: "Professeur titulaire · DIRO, Université de Montréal",
        researchAreaTags: [
          "Cryptographie",
          "Théorie de la complexité",
          "Protocoles quantiques",
        ],
        email: "salvail@iro.umontreal.ca",
        links: [
          {
            label: "Site web personnel",
            url: "https://www.iro.umontreal.ca/~salvail/Fiche%20personnelle.html",
          },
        ],
        bio: [
          "Louis Salvail est professeur titulaire au Département d'informatique et de recherche opérationnelle (DIRO) de l'Université de Montréal, et membre fondateur du LITQ.",
          "Il a obtenu son doctorat de l'Université de Montréal et a occupé des postes postdoctoraux à l'Université d'Aarhus et à l'Université de Waterloo avant de revenir à Montréal. Il est un expert internationalement reconnu en cryptographie quantique et en complexité computationnelle.",
        ],
        researchInterests: [
          "Cryptographie quantique et distribution de clés quantiques",
          "Protocoles quantiques à deux parties et multipartites",
          "Complexité computationnelle et réductions",
          "Transfert inconscient et schémas d'engagement",
          "Fondements de la sécurité cryptographique",
          "Primitives cryptographiques post-quantiques",
        ],
      },
    },
    {
      id: "frederic-dupuis",
      photo: "fred.jpg",
      profilePhotoFit: "contain",
      thumbnailPosition: "center",
      supervisedBy: null,
      supervises: [
        "gabriele-di-matteo",
        "paul-alexis-rodriguez",
        "felix-beaudoin",
      ],
      formerStudents: [],
      teaching: [
        {
          code: "IFT 6161",
          en: {
            name: "Théorie de l’information",
            detail: "Graduate · DIRO · Winter 2026",
          },
          fr: {
            name: "Théorie de l’information",
            detail: "Cycles supérieurs · DIRO · Hiver 2026",
          },
        },
        {
          code: "IFT 2125",
          en: {
            name: "Introduction à l'algorithmique",
            detail: "Undergraduate · DIRO · Fall 2025/Fall 2026",
          },
          fr: {
            name: "Introduction à l'algorithmique",
            detail: "Premier cycle · DIRO · Automne 2025/Automne 2026",
          },
        },
        {
          code: "IFT 6001",
          en: {
            name: "Formation préparatoire en algorithmique",
            detail: "Graduate · DIRO · Fall 2025",
          },
          fr: {
            name: "Formation préparatoire en algorithmique",
            detail: "Cycles supérieurs · DIRO · Automne 2025",
          },
        },
        {
          code: "IFT 2105",
          en: {
            name: "Introduction à l'informatique théorique",
            detail: "Undergraduate · DIRO · Fall 2025",
          },
          fr: {
            name: "Introduction à l'informatique théorique",
            detail: "Premier cycle · DIRO · Automne 2025",
          },
        },
      ],
      en: {
        eyebrow: "Faculty",
        nameFirst: "Frédéric",
        nameLast: "Dupuis",
        rank: "Associate Professor · DIRO, Université de Montréal",
        researchAreaTags: ["Quantum Cryptography", "Information Theory"],
        email: "dupuisf@iro.umontreal.ca",
        links: [
          {
            label: "Personal Website",
            url: "https://www.iro.umontreal.ca/~dupuisf/",
          },
        ],
        bio: [
          "Frédéric Dupuis is an associate professor at the computer science department of the University of Montreal. He is particularly interested in quantum information theory and in quantum cryptography.",
        ],
        researchInterests: [
          "Quantum Shannon theory",
          "Quantum cryptography",
          "Quantum information theory",
        ],
      },
      fr: {
        eyebrow: "Corps professoral",
        nameFirst: "Frédéric",
        nameLast: "Dupuis",
        rank: "Professeur agrégé · DIRO, Université de Montréal",
        researchAreaTags: [
          "Cryptographie quantique",
          "Théorie de l'information",
        ],
        email: "dupuis@iro.umontreal.ca",
        links: [
          {
            label: "Site web personnel",
            url: "https://www.iro.umontreal.ca/~dupuisf/",
          },
        ],
        bio: [],
        researchInterests: [
          "Théorie de Shannon quantique et capacités des canaux",
          "Mesures d'entropie à un coup et d'entropie lisse dans les systèmes quantiques",
          "Théorèmes de découplage et leurs applications",
          "Sécurité des protocoles de distribution de clés quantiques",
          "Extraction d'aléatoire et amplification de la confidentialité",
          "Théories des ressources quantiques et thermodynamique",
        ],
      },
    },
    {
      id: "gena-hahn",
      photo: "gena.jpg",
      supervisedBy: null,
      supervises: ["antony-leclerc", "gianluca-badiambile"],
      formerStudents: [],
      teaching: [
        {
          code: "IFT 6110",
          en: {
            name: "Graphes et réseaux",
            detail: "Graduate · DIRO · Winter 2026",
          },
          fr: {
            name: "Graphes et réseaux",
            detail: "Cycles supérieurs · DIRO · Hiver 2026",
          },
        },
      ],
      en: {
        eyebrow: "Faculty",
        nameFirst: "Gena",
        nameLast: "Hahn",
        rank: "Full Professor · DIRO, Université de Montréal",
        researchAreaTags: [
          "Graph Theory",
          "Combinatorics",
        ],
        email: "hahn@iro.umontreal.ca",
        links: [
          {
            label: "Personal Website",
            url: "https://www.iro.umontreal.ca/~hahn/",
          },
        ],
        bio: [],
        researchInterests: [],
      },
      fr: {
        eyebrow: "Corps professoral",
        nameFirst: "Gena",
        nameLast: "Hahn",
        rank: "Professeur titulaire · DIRO, Université de Montréal",
        researchAreaTags: [
          "Théorie des graphes",
          "Combinatoire",
          "Mathématiques discrètes",
        ],
        email: "hahn@iro.umontreal.ca",
        links: [{ label: "Site web personnel", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "hler-kristjansson",
      accentFirst: true,
      photo: "hler.jpg",
      thumbnailZoom: 1.2,
      thumbnailPosition: "center",
      thumbnailOrigin: "center center",
      supervisedBy: null,
      supervises: ["marek-arsenault", "daniel-bilsborrow", "taha-skiredj", "alexandre-charland", "sahil-naik", "philippe-allard-guerin"],
      formerStudents: [
        { name: "Thomas Vinet", role: "Master's research intern, Perimeter Institute & Télécom Paris, Feb–Aug 2024" },
        { name: "Yan Zhong", role: "PhD student, Johns Hopkins University (external project co-supervision), April 2023–Aug 2024" },
      ],
      teaching: [
        {
          code: "IFT 6760c",
          en: {
            name: "Séminaire en apprentissage automatique : Quantum computation, foundations and machine learning",
            detail: "Graduate · DIRO · Fall 2025/Fall 2026",
          },
          fr: {
            name: "Séminaire en apprentissage automatique : Quantum computation, foundations and machine learning",
            detail: "Cycles supérieurs · DIRO · Automne 2025/Automne 2026",
          },
        },
        {
          code: "IFT 6195",
          en: {
            name: "Sujets en informatique quantique",
            detail: "Graduate · DIRO · Summer 2027",
          },
          fr: {
            name: "Sujets en informatique quantique",
            detail: "Cycles supérieurs · DIRO · Été 2027",
          },
        },
      ],
      en: {
        eyebrow: "Faculty",
        nameFirst: "Hlér",
        nameLast: "Kristjánsson",
        rank: "Assistant Professor · DIRO, Université de Montréal",
        researchAreaTags: ["Quantum Algorithms", "Quantum Foundations"],
        email: "hler.kristjansson@umontreal.ca",
        links: [
          { label: "Personal Website", url: "https://hlerkristjansson.com" },
        ],
        bio: [
          "Hlér Kristjánsson is an Assistant Professor in Computer Science and a Research Chair of Institut Courtois at Université de Montréal, and an associate member of Mila – Québec AI Institute. He completed his PhD in Computer Science at the University Oxford in 2022 under Prof Giulio Chiribella and Prof Jonathan Barrett, and has held postdoctoral positions at the University of Tokyo and Perimeter Institute.",
          "His research sits at the intersection of quantum computing and quantum foundations, with a focus on causality in quantum theory, higher-order quantum computation, and quantum algorithms for the simulation of physical systems.",
        ],
        researchInterests: [
          "Quantum algorithms",
          "Causality in quantum theory and indefinite causal order",
          "Higher-order quantum computation",
          "Quantum simulation of physical systems",
          "Intersection of quantum computing and machine learning",
          "Quantum Shannon theory",
        ],
      },
      fr: {
        eyebrow: "Corps professoral",
        nameFirst: "Hlér",
        nameLast: "Kristjánsson",
        rank: "Professeur adjoint · DIRO, Université de Montréal",
        researchAreaTags: ["Algorithmes quantiques", "Fondements quantiques"],
        email: "kristjansson@iro.umontreal.ca",
        links: [
          { label: "Site web personnel", url: "https://hlerkristjansson.com" },
        ],
        bio: [
          "Hlér Kristjánsson est Professeur adjoint en informatique et Chaire de recherche de l'Institut Courtois à l'Université de Montréal, et membre associé de Mila – Institut québécois d'intelligence artificielle. Il a obtenu son doctorat en informatique à l'Université d'Oxford en 2022 sous la direction du Prof. Giulio Chiribella et du Prof. Jonathan Barrett, et a occupé des postes postdoctoraux à l'Université de Tokyo et à l'Institut Périmètre.",
          "Ses recherches se situent à l'intersection de l'informatique quantique et des fondements quantiques, avec un accent sur la causalité en théorie quantique, le calcul quantique d'ordre supérieur et les algorithmes quantiques pour la simulation de systèmes physiques.",
        ],
        researchInterests: [
          "Algorithmes quantiques",
          "Causalité en théorie quantique et ordre causal indéfini",
          "Calcul quantique d'ordre supérieur",
          "Simulation quantique de systèmes physiques",
          "Intersection de l'informatique quantique et de l'apprentissage automatique",
          "Théorie de l'information quantique de Shannon",
        ],
      },
    },
    {
      id: "dmitry-sokolov",
      photo: "dmitryS.jpg",
      supervisedBy: null,
      supervises: ["etienne-bouchard"],
      formerStudents: [],
      teaching: [
        {
          code: "IFT XXXX",
          en: {
            name: "TBC",
            detail: "TBC",
          },
          fr: {
            name: "TBC",
            detail: "TBC",
          },
        },
      ],
      en: {
        eyebrow: "Faculty",
        nameFirst: "Dmitry",
        nameLast: "Sokolov",
        rank: "Assistant Professor · DIRO, Université de Montréal",
        researchAreaTags: ["Complexity Theory"],
        email: "sokolov@iro.umontreal.ca",
        links: [],
        bio: [
          "2026 –, Assistant Professor (UdeM)",
          "2022 – 2026, Researcher (EPFL)",
          "2020 – 2022, Associate Professor (St. Petersburg State University)",
          "2017 – 2020, PostDoc (KTH, Lund/Copenhagen University)",
          "2016 – 2022, Researcher (Steklov Institute of Mathematics in St. Petersburg)",
          "2015, PhD in Mathematics (Steklov Institute of Mathematics in St. Petersburg)",
        ],
        researchInterests: [
          "Proof Complexity",
          "Complexity Theory",
          "Communication Complexity",
          "Combinatorics",
          "Discrete Mathematics",
        ],
      },
      fr: {
        eyebrow: "Corps professoral",
        nameFirst: "Dmitry",
        nameLast: "Sokolov",
        rank: "Professeur adjoint · DIRO, Université de Montréal",
        researchAreaTags: ["Théorie de la complexité"],
        email: "sokolov@iro.umontreal.ca",
        links: [],
        bio: [
          "2026 –, Professeur adjoint (UdeM)",
          "2022 – 2026, Chercheur (EPFL)",
          "2020 – 2022, Professeur associé (Université d'État de Saint-Pétersbourg)",
          "2017 – 2020, Postdoctorant (KTH, Université de Lund/Copenhague)",
          "2016 – 2022, Chercheur (Institut Steklov de Mathématiques de Saint-Pétersbourg)",
          "2015, Doctorat en mathématiques (Institut Steklov de Mathématiques de Saint-Pétersbourg)",
        ],
        researchInterests: [
          "Complexité des preuves",
          "Théorie de la complexité",
          "Complexité de la communication",
          "Combinatoire",
          "Mathématiques discrètes",
        ],
      },
    },
    {
      id: "marek-arsenault",
      photo: "Marek.jpg",
      supervisedBy: null,
      supervises: [],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "Master's Student",
        nameFirst: "Marek",
        nameLast: "Arsenault",
        rank: "Master's Student · DIRO, Université de Montréal",
        researchAreaTags: ["Quantum Algorithms"],
        links: [{ label: "Personal Website", url: "#" }],
        bio: [
          "I completed my Bachelor's degree in Physics and Computer Science at Université de Montréal, and I am currently finishing my Master's thesis.",
        ],
        researchInterests: [
          "I am broadly interested in Quantum Functional Programming, with the goal of developing new algorithms to transform data encoded in quantum devices given as black boxes. More precisely, my approach leverages product formulas, such as qDrift, to construct functions of Hamiltonians, a process that can be understood as a linearised version of well-known algorithms such as QSP and QSVT.",
        ],
      },
      fr: {
        eyebrow: "Étudiant(e) à la maîtrise",
        nameFirst: "Marek",
        nameLast: "Arsenault",
        rank: "Étudiant(e) à la maîtrise · DIRO, Université de Montréal",
        researchAreaTags: ["Algorithmes quantiques"],
        links: [{ label: "Site web personnel", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "daniel-bilsborrow",
      photo: "Dan.jpg",
      supervisedBy: ["hler-kristjansson"],
      supervises: [],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "PhD Student",
        nameFirst: "Daniel",
        nameLast: "Bilsborrow",
        rank: "PhD Student · DIRO, Université de Montréal",
        researchAreaTags: ["Quantum Algorithms", "Quantum Foundations"],
        links: [{ label: "Personal Website", url: "#" }],
        bio: [],
        researchInterests: [],
      },
      fr: {
        eyebrow: "Doctorant(e)",
        nameFirst: "Daniel",
        nameLast: "Bilsborrow",
        rank: "Doctorant(e) · DIRO, Université de Montréal",
        researchAreaTags: ["Algorithmes quantiques", "Fondements quantiques"],
        links: [{ label: "Site web personnel", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "taha-skiredj",
      photo: "Taha.jpg",
      supervisedBy: null,
      supervises: [],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "Master's Student",
        nameFirst: "Taha",
        nameLast: "Skiredj",
        rank: "Master's Student · DIRO, Université de Montréal",
        researchAreaTags: ["Quantum Foundations"],
        links: [{ label: "Personal Website", url: "#" }],
        bio: [],
        researchInterests: [],
      },
      fr: {
        eyebrow: "Étudiant(e) à la maîtrise",
        nameFirst: "Taha",
        nameLast: "Skiredj",
        rank: "Étudiant(e) à la maîtrise · DIRO, Université de Montréal",
        researchAreaTags: ["Fondements quantiques"],
        links: [{ label: "Site web personnel", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "alexandre-charland",
      photo: "AlexCharland.JPG",
      supervisedBy: ["hler-kristjansson"],
      supervises: [],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "Master's Student",
        nameFirst: "Alexandre",
        nameLast: "Charland",
        rank: "Master's Student · DIRO, Université de Montréal",
        researchAreaTags: ["Quantum Foundations"],
        links: [{ label: "Personal Website", url: "#" }],
        bio: [],
        researchInterests: [],
      },
      fr: {
        eyebrow: "Étudiant(e) à la maîtrise",
        nameFirst: "Alexandre",
        nameLast: "Charland",
        rank: "Étudiant(e) à la maîtrise · DIRO, Université de Montréal",
        researchAreaTags: ["Fondements quantiques"],
        links: [{ label: "Site web personnel", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "samuel-ducharme",
      photo: "samDucharme.jpg",
      supervisedBy: null,
      supervises: [],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "PhD Student",
        nameFirst: "Samuel",
        nameLast: "Ducharme",
        rank: "PhD Student · DIRO, Université de Montréal",
        researchAreaTags: ["Quantum Cryptography"],
        links: [{ label: "Personal Website", url: "#" }],
        bio: [],
        researchInterests: [],
      },
      fr: {
        eyebrow: "Doctorant(e)",
        nameFirst: "Samuel",
        nameLast: "Ducharme",
        rank: "Doctorant(e) · DIRO, Université de Montréal",
        researchAreaTags: ["Cryptographie quantique"],
        links: [{ label: "Site web personnel", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "charlie-pilon-senterre",
      photo: null,
      supervisedBy: ["louis-salvail"],
      supervises: [],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "PhD Student",
        nameFirst: "Charlie",
        nameLast: "Pilon-Senterre",
        rank: "PhD Student · DIRO, Université de Montréal",
        researchAreaTags: ["Quantum Cryptography"],
        links: [{ label: "Personal Website", url: "#" }],
        bio: [],
        researchInterests: [],
      },
      fr: {
        eyebrow: "Doctorant(e)",
        nameFirst: "Charlie",
        nameLast: "Pilon-Senterre",
        rank: "Doctorant(e) · DIRO, Université de Montréal",
        researchAreaTags: ["Cryptographie quantique"],
        links: [{ label: "Site web personnel", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "linhui-fu",
      photo: null,
      supervisedBy: ["philippe-lamontagne"],
      supervises: [],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "PhD Student",
        nameFirst: "Linhui",
        nameLast: "Fu",
        rank: "PhD Student · DIRO, Université de Montréal",
        researchAreaTags: ["Quantum Cryptography"],
        links: [{ label: "Personal Website", url: "#" }],
        bio: [],
        researchInterests: [],
      },
      fr: {
        eyebrow: "Doctorant(e)",
        nameFirst: "Linhui",
        nameLast: "Fu",
        rank: "Doctorant(e) · DIRO, Université de Montréal",
        researchAreaTags: ["Cryptographie quantique"],
        links: [{ label: "Site web personnel", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "remi-ligez",
      photo: null,
      supervisedBy: null,
      supervises: [],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "PhD Student",
        nameFirst: "Rémi",
        nameLast: "Ligez",
        rank: "PhD Student · DIRO, Université de Montréal",
        researchAreaTags: ["Quantum Cryptography"],
        links: [{ label: "Personal Website", url: "#" }],
        bio: [],
        researchInterests: [],
      },
      fr: {
        eyebrow: "Doctorant(e)",
        nameFirst: "Rémi",
        nameLast: "Ligez",
        rank: "Doctorant(e) · DIRO, Université de Montréal",
        researchAreaTags: ["Cryptographie quantique", "Fondements quantiques"],
        links: [{ label: "Site web personnel", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "devashish-tupkary",
      photo: null,
      supervisedBy: null,
      supervises: [],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "Postdoc",
        nameFirst: "Devashish",
        nameLast: "Tupkary",
        rank: "Postdoctoral Researcher · DIRO, Université de Montréal",
        researchAreaTags: ["Quantum Cryptography"],
        email: "devashish.tupkary@umontreal.ca",
        links: [
          {
            label: "Personal Website",
            url: "https://diro.umontreal.ca/repertoire-departement/professeurs/fiche/in/in27374/sg/Louis%20Salvail/",
          },
        ],
        bio: [],
        researchInterests: [],
      },
      fr: {
        eyebrow: "Postdoc",
        nameFirst: "Devashish",
        nameLast: "Tupkary",
        rank: "Chercheur Postdoctoral · DIRO, Université de Montréal",
        researchAreaTags: ["Cryptographie Quantique"],
        email: "devashish.tupkary@umontreal.ca",
        links: [
          {
            label: "Site web personnel",
            url: "https://diro.umontreal.ca/repertoire-departement/professeurs/fiche/in/in27374/sg/Louis%20Salvail/",
          },
        ],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "sahil-naik",
      photo: null,
      supervisedBy: ["hler-kristjansson"],
      supervises: [],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "Postdoc",
        nameFirst: "Sahil",
        nameLast: "Naik",
        rank: "Postdoctoral Researcher · DIRO, Université de Montréal",
        researchAreaTags: ["Quantum Foundations", "Quantum Information", "Indefinite causal order", "Higher order Quantum Transformations"],
        links: [{ label: "Personal Website", url: "#" }],
        bio: [
          "I am a Postdoctoral Fellow at the Université de Montréal (UdeM). I obtained my Master's degree in Physics from the Indian Institute of Science Education and Research (IISER) Thiruvananthapuram, India, and completed my PhD at the S. N. Bose National Centre for Basic Sciences, Kolkata, under the affiliation of Presidency University, India.",
          "My doctoral research focused on General Probabilistic Theories (GPTs) and their role in understanding quantum phenomena from both foundational and information-theoretic perspectives. During my PhD, I investigated questions related to nonlocality, state discrimination, measurement incompatibility, and information-processing tasks within generalized physical theories. I also studied how novel features of quantum theory, such as indefinite causal order, can be useful in information-processing tasks.",
        ],
        researchInterests: [
          "<p>My research interests are broadly centered around the foundations and information-theoretic aspects of quantum theory. I am particularly interested in the intriguing phenomena of indefinite causal order arising in higher order quantum theory and the implications for quantum information processing. I am also interested in higher-order transformations, which provide a generalized framework extending the notion of quantum channels and offer new ways of understanding transformations between physical processes.</p>" +
          "<p>An area I am particularly interested in exploring is the role of higher-order transformations as computational resources. I would like to investigate how such generalized transformations can be harnessed for computation and whether they can provide new perspectives on the foundations and broader theoretical landscape of computer science.</p>" +
          "<p>More broadly, I am interested in exploring the operational and foundational principles underlying quantum theory and understanding how these principles can lead to novel approaches to quantum information processing.</p>",
        ],
      },
      fr: {
        eyebrow: "Postdoc",
        nameFirst: "Sahil",
        nameLast: "Naik",
        rank: "Chercheur Postdoctoral · DIRO, Université de Montréal",
        researchAreaTags: ["Théorie de l'information quantique", "Fondements quantiques", "Théorie quantique d'ordre supérieur"],
        links: [{ label: "Site web personnel", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "anantha-krishnan-sunilkumar",
      photo: null,
      supervisedBy: null,
      supervises: [],
      formerStudents: [],
      teaching: [],
      externalSupervisors: [
        {
          name: "Guillaume Rabusseau",
          title: "Assistant Professor · Mila & DIRO, Université de Montréal",
          url: "https://www-labs.iro.umontreal.ca/~grabus/",
        },
      ],
      en: {
        eyebrow: "PhD Student",
        nameFirst: "Anantha Krishnan",
        nameLast: "Sunilkumar",
        rank: "PhD Student · DIRO, Université de Montréal",
        researchAreaTags: ["Quantum Information Theory"],
        links: [{ label: "Personal Website", url: "#" }],
        bio: [],
        researchInterests: [],
      },
      fr: {
        eyebrow: "Doctorant(e)",
        nameFirst: "Anantha Krishnan",
        nameLast: "Sunilkumar",
        rank: "Doctorant(e) · DIRO, Université de Montréal",
        researchAreaTags: ["Théorie de l'information quantique"],
        links: [{ label: "Site web personnel", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "philippe-allard-guerin",
      photo: null,
      supervisedBy: ["hler-kristjansson"],
      supervises: [],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "Postdoc",
        nameFirst: "Philippe",
        nameLast: "Allard Guérin",
        rank: "Senior Research Associate · Université de Montréal · June 2026–",
        researchAreaTags: [],
        links: [{ label: "Personal Website", url: "#" }],
        bio: [],
        researchInterests: [],
      },
      fr: {
        eyebrow: "Postdoc",
        nameFirst: "Philippe",
        nameLast: "Allard Guérin",
        rank: "Associé de recherche senior · Université de Montréal · Juin 2026–",
        researchAreaTags: [],
        links: [{ label: "Site web personnel", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "leo-londeix-pagnard",
      photo: null,
      incoming: true,
      supervisedBy: ["hler-kristjansson"],
      supervises: [],
      formerStudents: [],
      teaching: [],
      externalSupervisors: [
        {
          name: "Michel Côté",
          title: "Professor · Department of Physics, Université de Montréal",
          url: "https://phys.umontreal.ca/repertoire-departement/professeurs/professeur/in/in14301/sg/Michel%20C%C3%B4t%C3%A9/",
        },
        {
          name: "Matthias Ernzerhof",
          title: "Professor · Department of Chemistry, Université de Montréal",
          url: "https://chimie.umontreal.ca/english/department-directory/professors/professor/in/in14628/sg/Matthias%20Ernzerhof/",
        },
      ],
      en: {
        eyebrow: "Incoming Member",
        nameFirst: "Léo",
        nameLast: "Londeix-Pagnard",
        rank: "PhD Student · Université de Montréal · Sep 2026",
        researchAreaTags: [],
        links: [{ label: "Personal Website", url: "#" }],
        bio: [],
        researchInterests: [],
      },
      fr: {
        eyebrow: "Membre à venir",
        nameFirst: "Léo",
        nameLast: "Londeix-Pagnard",
        rank: "Doctorant(e) · Université de Montréal · Sept. 2026",
        researchAreaTags: [],
        links: [{ label: "Site web personnel", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "maelys-viegas",
      photo: null,
      incoming: true,
      supervisedBy: ["hler-kristjansson"],
      supervises: [],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "Incoming Member",
        nameFirst: "Maelys",
        nameLast: "Viegas",
        rank: "Master's Research Intern · Université de Montréal & Télécom Paris · Mar 2027",
        researchAreaTags: [],
        links: [{ label: "Personal Website", url: "#" }],
        bio: [],
        researchInterests: [],
      },
      fr: {
        eyebrow: "Membre à venir",
        nameFirst: "Maelys",
        nameLast: "Viegas",
        rank: "Stagiaire de recherche à la maîtrise · Université de Montréal & Télécom Paris · Mars 2027",
        researchAreaTags: [],
        links: [{ label: "Site web personnel", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "pierre-mckenzie",
      photo: null,
      supervisedBy: null,
      supervises: ["jean-claude-desrosiers"],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "Former Faculty",
        nameFirst: "Pierre",
        nameLast: "McKenzie",
        rank: "Full Professor · DIRO, Université de Montréal",
        researchAreaTags: ["Complexity Theory"],
        email: "mckenzie@iro.umontreal.ca",
        links: [{ label: "Personal Website", url: "https://www.iro.umontreal.ca/~mckenzie/" }],
        bio: [],
        researchInterests: [],
      },
      fr: {
        eyebrow: "Ancien corps professoral",
        nameFirst: "Pierre",
        nameLast: "McKenzie",
        rank: "Professeur titulaire · DIRO, Université de Montréal",
        researchAreaTags: ["Théorie de la complexité"],
        email: "mckenzie@iro.umontreal.ca",
        links: [{ label: "Site web personnel", url: "https://www.iro.umontreal.ca/~mckenzie/" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "philippe-lamontagne",
      photo: "PhilippeLamontagne.jpg",
      profilePhotoFit: "contain",
      supervisedBy: null,
      supervises: ["alexey-norkin", "linhui-fu", "ding-wen-li"],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "Faculty",
        nameFirst: "Philippe",
        nameLast: "Lamontagne",
        rank: "Adjunct Professor · DIRO, Université de Montréal",
        researchAreaTags: ["Quantum Cryptography"],
        email: "philippe.lamontagne.1@umontreal.ca",
        links: [
          {
            label: "Personal Website",
            url: "https://cnrc.canada.ca/en/corporate/contact-us/nrc-directory-science-professionals/philippe-lamontagne",
          },
        ],
        bio: [
          "I am a Research officer in the Cryptography and Quantum Computing team of the Digital Technologies research center and adjunct professor at UdeM. My research expertise is in quantum cryptography. I am interested in exploiting quantum information for advanced cryptographic tasks form lesser assumptions.",
          "I also do research on the security of classical cryptography against quantum adversaries, also known as post-quantum cryptography. I am also interested in cryptographic solutions to privacy.",
        ],
        researchInterests: [
          "Quantum-secure cryptographic protocols",
          "Oblivious transfer and secure multiparty computation",
          "Post-quantum cryptography and lattice-based constructions",
          "Randomness extraction and privacy amplification",
          "Security reductions and composable security",
          "Quantum information-theoretic security",
        ],
      },
      fr: {
        eyebrow: "Corps professoral",
        nameFirst: "Philippe",
        nameLast: "Lamontagne",
        rank: "Professeur adjoint · DIRO, Université de Montréal",
        researchAreaTags: [
          "Cryptographie quantique",
          "Calcul sécurisé",
          "Cryptographie post-quantique",
        ],
        email: "philippe.lamontagne2@cnrc-nrc.gc.ca",
        links: [
          {
            label: "Site web personnel",
            url: "https://cnrc.canada.ca/fr/organisation/contactez-nous/repertoire-scientifiques-cnrc/philippe-lamontagne",
          },
        ],
        bio: [
          "Je suis agent de recherche dans l'équipe de cryptographie et de calcul quantique centre de recherche en technologies numériques et professeur associé à l'UdeM. Mon expertise de recherche est la cryptographie quantique. Je m'intéresse à l'exploitation de l'information quantique pour des tâches cryptographiques avancées à partir d'hypothèses réduites.",
          "Je fais également de la recherche en cryptographie post-quantique, la branche de la cryptographie classique qui s'intéresse à la sécurité face à un adversaire quantique. Je m'intéresse aussi aux solutions cryptographiques au calcul respectueux de la vie privée.",
        ],
        researchInterests: [
          "Protocoles cryptographiques à sécurité quantique",
          "Transfert inconscient et calcul multipartite sécurisé",
          "Cryptographie post-quantique et constructions basées sur les réseaux",
          "Extraction d'aléatoire et amplification de la confidentialité",
          "Réductions de sécurité et sécurité composable",
          "Sécurité quantique basée sur la théorie de l'information",
        ],
      },
    },
    {
      id: "muxue-guo",
      photo: null,
      supervisedBy: ["gilles-brassard"],
      supervises: [],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "PhD Student",
        nameFirst: "Muxue",
        nameLast: "Guo",
        rank: "PhD Student · DIRO, Université de Montréal",
        researchAreaTags: ["Quantum Cryptography"],
        links: null,
        bio: [],
        researchInterests: [],
      },
      fr: {
        eyebrow: "Doctorant(e)",
        nameFirst: "Muxue",
        nameLast: "Guo",
        rank: "Doctorant(e) · DIRO, Université de Montréal",
        researchAreaTags: ["Cryptographie quantique"],
        links: [{ label: "Site web personnel", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "mohammed-barhoush",
      photo: null,
      supervisedBy: ["louis-salvail"],
      supervises: [],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "PhD Student",
        nameFirst: "Mohammed",
        nameLast: "Barhoush",
        rank: "PhD Student · DIRO, Université de Montréal",
        researchAreaTags: ["Quantum Cryptography"],
        links: [{ label: "Personal Website", url: "#" }],
        bio: [],
        researchInterests: [],
      },
      fr: {
        eyebrow: "Doctorant(e)",
        nameFirst: "Mohammed",
        nameLast: "Barhoush",
        rank: "Doctorant(e) · DIRO, Université de Montréal",
        researchAreaTags: ["Cryptographie quantique"],
        links: [{ label: "Site web personnel", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "louis-charles-thibodeau",
      photo: null,
      supervisedBy: ["louis-salvail"],
      supervises: [],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "PhD Student",
        nameFirst: "Louis-Charles",
        nameLast: "Thibodeau",
        rank: "PhD Student · DIRO, Université de Montréal",
        researchAreaTags: ["Quantum Cryptography"],
        links: [{ label: "Personal Website", url: "#" }],
        bio: [],
        researchInterests: [],
      },
      fr: {
        eyebrow: "Doctorant(e)",
        nameFirst: "Louis-Charles",
        nameLast: "Thibodeau",
        rank: "Doctorant(e) · DIRO, Université de Montréal",
        researchAreaTags: ["Cryptographie quantique"],
        links: [{ label: "Site web personnel", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "florian-le-mouel",
      photo: null,
      supervisedBy: ["louis-salvail"],
      supervises: [],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "PhD Student",
        nameFirst: "Florian",
        nameLast: "Le Mouël",
        rank: "PhD Student · DIRO, Université de Montréal",
        researchAreaTags: ["Quantum Cryptography"],
        links: [{ label: "Personal Website", url: "#" }],
        bio: [],
        researchInterests: [],
      },
      fr: {
        eyebrow: "Doctorant(e)",
        nameFirst: "Florian",
        nameLast: "Le Mouël",
        rank: "Doctorant(e) · DIRO, Université de Montréal",
        researchAreaTags: ["Cryptographie quantique"],
        links: [{ label: "Site web personnel", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "khaireddine-medhioub",
      photo: null,
      supervisedBy: ["louis-salvail"],
      supervises: [],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "PhD Student",
        nameFirst: "Khaireddine",
        nameLast: "Medhioub",
        rank: "PhD Student · DIRO, Université de Montréal",
        researchAreaTags: ["Quantum Cryptography"],
        links: [{ label: "Personal Website", url: "#" }],
        bio: [],
        researchInterests: [],
      },
      fr: {
        eyebrow: "Doctorant(e)",
        nameFirst: "Khaireddine",
        nameLast: "Medhioub",
        rank: "Doctorant(e) · DIRO, Université de Montréal",
        researchAreaTags: ["Cryptographie quantique"],
        links: [{ label: "Site web personnel", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "gabriele-di-matteo",
      photo: null,
      supervisedBy: ["frederic-dupuis"],
      supervises: [],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "PhD Student",
        nameFirst: "Gabriele",
        nameLast: "Di Matteo",
        rank: "PhD Student · DIRO, Université de Montréal",
        researchAreaTags: ["Quantum Cryptography", "Information Theory"],
        links: [{ label: "Personal Website", url: "#" }],
        bio: [],
        researchInterests: [],
      },
      fr: {
        eyebrow: "Doctorant(e)",
        nameFirst: "Gabriele",
        nameLast: "Di Matteo",
        rank: "Doctorant(e) · DIRO, Université de Montréal",
        researchAreaTags: [
          "Cryptographie quantique",
          "Théorie de l'information",
        ],
        links: [{ label: "Site web personnel", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "paul-alexis-rodriguez",
      photo: null,
      supervisedBy: ["frederic-dupuis"],
      supervises: [],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "PhD Student",
        nameFirst: "Paul-Alexis",
        nameLast: "Rodriguez",
        rank: "PhD Student · DIRO, Université de Montréal",
        researchAreaTags: ["Quantum Cryptography", "Information Theory"],
        links: [{ label: "Personal Website", url: "#" }],
        bio: [],
        researchInterests: [],
      },
      fr: {
        eyebrow: "Doctorant(e)",
        nameFirst: "Paul-Alexis",
        nameLast: "Rodriguez",
        rank: "Doctorant(e) · DIRO, Université de Montréal",
        researchAreaTags: [
          "Cryptographie quantique",
          "Théorie de l'information",
        ],
        links: [{ label: "Site web personnel", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "alexey-norkin",
      photo: null,
      supervisedBy: ["philippe-lamontagne"],
      supervises: [],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "PhD Student",
        nameFirst: "Alexey",
        nameLast: "Norkin",
        rank: "PhD Student · DIRO, Université de Montréal",
        researchAreaTags: ["Quantum Cryptography"],
        links: [{ label: "Personal Website", url: "#" }],
        bio: [],
        researchInterests: [],
      },
      fr: {
        eyebrow: "Doctorant(e)",
        nameFirst: "Alexey",
        nameLast: "Norkin",
        rank: "Doctorant(e) · DIRO, Université de Montréal",
        researchAreaTags: ["Cryptographie quantique"],
        links: [{ label: "Site web personnel", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "ding-wen-li",
      photo: null,
      supervisedBy: ["philippe-lamontagne"],
      supervises: [],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "Master's Student",
        nameFirst: "Ding Wen",
        nameLast: "Li",
        rank: "Master's Student · DIRO, Université de Montréal",
        researchAreaTags: ["Quantum Cryptography"],
        links: [{ label: "Personal Website", url: "#" }],
        bio: [],
        researchInterests: [],
      },
      fr: {
        eyebrow: "Étudiant(e) à la maîtrise",
        nameFirst: "Ding Wen",
        nameLast: "Li",
        rank: "Étudiant(e) à la maîtrise · DIRO, Université de Montréal",
        researchAreaTags: ["Cryptographie quantique"],
        links: [{ label: "Site web personnel", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "antony-leclerc",
      photo: null,
      supervisedBy: ["gena-hahn"],
      supervises: [],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "Master's Student",
        nameFirst: "Antony",
        nameLast: "Leclerc",
        rank: "Master's Student · DIRO, Université de Montréal",
        researchAreaTags: [
          "Graph Theory",
          "Combinatorics",
        ],
        links: [{ label: "Personal Website", url: "#" }],
        bio: [],
        researchInterests: [],
      },
      fr: {
        eyebrow: "Étudiant(e) à la maîtrise",
        nameFirst: "Antony",
        nameLast: "Leclerc",
        rank: "Étudiant(e) à la maîtrise · DIRO, Université de Montréal",
        researchAreaTags: [
          "Théorie des graphes",
          "Combinatoire",
          "Mathématiques discrètes",
        ],
        links: [{ label: "Site web personnel", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "gianluca-badiambile",
      photo: null,
      supervisedBy: ["gena-hahn"],
      supervises: [],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "Master's Student",
        nameFirst: "Gianluca",
        nameLast: "Badiambile",
        rank: "Master's Student · DIRO, Université de Montréal",
        researchAreaTags: [
          "Graph Theory",
          "Combinatorics",
        ],
        email: "gianluca.badiambile@gmail.com",
        links: [{ label: "Personal Website", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "etienne-bouchard",
      photo: null,
      supervisedBy: ["dmitry-sokolov"],
      supervises: [],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "Master's Student",
        nameFirst: "Étienne",
        nameLast: "Bouchard",
        rank: "Master's Student · DIRO, Université de Montréal",
        researchAreaTags: ["Complexity Theory"],
        links: [{ label: "Personal Website", url: "#" }],
        bio: [],
        researchInterests: [],
      },
      fr: {
        eyebrow: "Étudiant(e) à la maîtrise",
        nameFirst: "Étienne",
        nameLast: "Bouchard",
        rank: "Étudiant(e) à la maîtrise · DIRO, Université de Montréal",
        researchAreaTags: ["Théorie de la complexité"],
        links: [{ label: "Site web personnel", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "felix-beaudoin",
      photo: null,
      supervisedBy: ["frederic-dupuis"],
      supervises: [],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "Master's Student",
        nameFirst: "Félix",
        nameLast: "Beaudoin",
        rank: "Master's Student · DIRO, Université de Montréal",
        researchAreaTags: ["Quantum Cryptography", "Information Theory"],
        links: [{ label: "Personal Website", url: "#" }],
        bio: [],
        researchInterests: [],
      },
      fr: {
        eyebrow: "Étudiant(e) à la maîtrise",
        nameFirst: "Félix",
        nameLast: "Beaudoin",
        rank: "Étudiant(e) à la maîtrise · DIRO, Université de Montréal",
        researchAreaTags: [
          "Cryptographie quantique",
          "Théorie de l'information",
        ],
        links: [{ label: "Site web personnel", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
    {
      id: "jean-claude-desrosiers",
      photo: null,
      supervisedBy: ["pierre-mckenzie"],
      supervises: [],
      formerStudents: [],
      teaching: [],
      en: {
        eyebrow: "Master's Student",
        nameFirst: "Jean-Claude",
        nameLast: "Desrosiers",
        rank: "Master's Student · DIRO, Université de Montréal",
        researchAreaTags: [],
        links: [{ label: "Personal Website", url: "#" }],
        bio: [],
        researchInterests: [],
      },
      fr: {
        eyebrow: "Étudiant(e) à la maîtrise",
        nameFirst: "Jean-Claude",
        nameLast: "Desrosiers",
        rank: "Étudiant(e) à la maîtrise · DIRO, Université de Montréal",
        researchAreaTags: [],
        links: [{ label: "Site web personnel", url: "#" }],
        bio: [],
        researchInterests: [],
      },
    },
  ],
  pastPostdocs: [
    {
      name: "Sayantan Chakraborty",
      years: "2025",
      supervisor: "Frédéric Dupuis",
      note: "Now at University of Cologne",
    },
    {
      name: "Sam Kuypers",
      years: "2024-2025",
      supervisor: "Gilles Brassard",
      note: "TBC",
    },
  ],
  pastStudents: [
    {
      name: "Sophie Berthelette",
      degree: "PhD",
      year: "2025",
      supervisor: "Gilles Brassard",
      note: "Now at Università della Svizzera italiana",
    },
    {
      name: "Ashutosh Marwah",
      degree: "PhD",
      year: "2025",
      supervisor: "Frédéric Dupuis",
      note: "Now at Ingonyama",
    },
  ],
};
